animáció kész
Training360-JavaScript/angular-zaro-projekt-the-new-octal-8 pull request #20
Opened 2022-02-17 12:41 UTC by keszigabesz

2022-02-20 04:53 UTC, MarkFazekas requested changes

2022-02-20 04:53 UTC, MarkFazekas commented on the-new-octal/src/app/page/addresses/addresses.component.html
> +                      [class.table-active]="sort === column.reference" (click)="onChangeOrder(column.reference)">
Hogyha nem fér ki egy képernyőre az egész egymás mellé, akkor atribútomonként törjük egymás alá.

2022-02-20 04:53 UTC, MarkFazekas commented on the-new-octal/src/app/common/loading-animation-colors/loading-animation-colors.component.ts
> +  @Input() list$ = new Observable;
2x kérjük le ugyanazt a végpontot ugyanazt az eredményt kapva.
Egy esetlegesség miatt jelenik meg az adat később.

Vagy legyen @Input @Output és a list az legyen Output.
Vagy akár egy ng-container-be csinálhatod az `(list$ | async) as list`-et amit megkap ez a komponens és a későbbi `*ngFor`

![image](https://user-images.githubusercontent.com/10902799/154828744-6db2ff77-6bfd-4434-ade0-38b86f8d6a5e.png)

2022-02-20 04:53 UTC, MarkFazekas commented on the-new-octal/src/styles.scss
> +#loader {
Nem mindenhol ő a top.
Egy hátteret rakhatnánk elé, hogy elüssön minden képernyőn a háttértől.

![image](https://user-images.githubusercontent.com/10902799/154828851-d2492635-0947-4a95-a517-4eaa60218feb.png)

2022-02-20 04:53 UTC, MarkFazekas commented on the-new-octal/src/app/page/edit-address/edit-address.component.html
> +<app-loading-edit [editedObject]="editedObject"></app-loading-edit>
Ez az egyik megoldási lehetősélg a listához is.

2022-02-20 04:53 UTC, MarkFazekas commented on the-new-octal/src/app/common/loading-edit/loading-edit.component.html
> +</div>
Onnantól, hogy nem lesz Observable és nem Observable-s megoldás, elég lesz 1 töltő komponens

2022-02-20 04:53 UTC, MarkFazekas commented on the-new-octal/src/styles.scss
> +#loader {
Mivel 1 komponens lesz, így annak az scss fájljába rakjuk

2022-02-20 22:58 UTC, MarkFazekas requested changes
Legkorábban bemutató és conflict feloldás után mehet be. (még egy review hogy jó lett-e a javítás)

2022-02-21 08:32 UTC, keszigabesz commented
feloldottam a conlictokat lehet mergelni

2022-02-21 17:40 UTC, merged

2022-02-21 17:40 UTC, szabozsolt20 commented
Bátorkodtam.