37-hotfix-validálásban-néhány-helyen-hiányzik-a-cimke-ezeket-pótolom
Training360-JavaScript/angular-zaro-projekt-the-new-octal-8 pull request #21
Opened 2022-02-18 14:12 UTC by keszigabesz

Kéz helyen a hiányzó validációt beraktam, ezért hotfix, mert ez kötelező elem lenne. 
A táblázatok sorbarendezésénél kicseréltem a nyilat.

2022-02-20 22:57 UTC, MarkFazekas requested changes
Bemutató és conflict feloldás után mehet be.
A kódformázásokat reverteld.

2022-02-21 08:19 UTC, keszigabesz commented
feloldottam a conflictocat, lehet mergelni

2022-02-21 08:20 UTC, keszigabesz commented
feloldottam a conflictocat lehet mergelni

2022-02-21 17:53 UTC, szabozsolt20 commented
Bátorságpróba No.:2. :)

2022-02-21 17:53 UTC, merged